/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Custom colors mapping to CSS variables
        'bg-base': 'var(--bg-base)',
        'bg-surface': 'var(--bg-surface)',
        'bg-elevated': 'var(--bg-elevated)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'brand-primary': 'var(--brand-primary)',
        'brand-cta-primary': 'var(--brand-cta-primary)',
        'brand-cta-secondary': 'var(--brand-cta-secondary)',
        'brand-link': 'var(--brand-link)',
        'brand-contrast': 'var(--brand-contrast)',
        'border-subtle': 'var(--border-subtle)',
        'focus-ring': 'var(--focus-ring)',
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
        'display': 'clamp(2.5rem, 6vw, 4.5rem)',
        'h1': 'clamp(2.25rem, 5vw, 3.5rem)',
        'h2': 'clamp(1.75rem, 4vw, 2.75rem)',
        'h3': 'clamp(1.5rem, 3vw, 2.25rem)',
        'body': '1.0625rem',
        'small': '0.9375rem',
        'caption': '0.75rem',
      },
      spacing: {
        '1': 'var(--space-xs)',
        '2': 'var(--space-sm)',
        '3': 'var(--space-md)',
        '4': 'var(--space-lg)',
        '5': 'var(--space-xl)',
        '6': 'var(--space-2xl)',
        '7': 'var(--space-3xl)',
        '8': 'var(--space-4xl)',
        '9': 'var(--space-5xl)',
        'section-mobile': '3rem',
        'section-desktop': '6rem',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        full: '9999px',
      },
      boxShadow: {
        DEFAULT: 'var(--shadow-default)',
        sm: 'var(--shadow-sm)',
      },
      maxWidth: {
        'prose': '72ch',
        'md-container': '768px',
        '6xl': '72rem',
        '7xl': '80rem',
      },
      lineHeight: {
        'heading': 'var(--line-height-heading)',
        'body': 'var(--line-height-body)',
      },
    },
  },
  plugins: [],
};
